### ISSUE TITLE
Bug: global-buffer-overflow on test_coap_server.c:server_handle_reset

### ISSUE THREAD

**Issue by gazer-star** [keith-cullen/FreeCoAP#34]
## Build
Build the test_coap_server with ASAN flag
```bash
export CFLAGS=-Wall -g fsanitize=address
make dtls=n
```

## Run
Run   `test_coap_server` and `test_coap_client` in two terminal

## Analyze
A global-buffer-overflow happend on `memcpy(app_level_blockwise_buf, app_level_blockwise_def_val, sizeof(app_level_blockwise_buf));`.
`sizeof(app_level_blockwise_buf` is 40, but the `app_level_blockwise_def_val` point to `""`

```c
/**
 *  @brief Buffer used for application-level blockwise transfers
 */
static char *app_level_blockwise_def_val = "";
static char app_level_blockwise_buf[APP_LEVEL_BLOCKWISE_BUF_LEN] = {0};
...

static int server_handle_reset(coap_server_trans_t *trans, coap_msg_t *req, coap_msg_t *resp)
{
    coap_log_notice("Resetting to a known state");

    memset(regular_buf, 0, sizeof(regular_buf));
    memcpy(regular_buf, regular_def_val, sizeof(regular_buf));

    memset(app_level_blockwise_buf, 0, sizeof(app_level_blockwise_buf));
    memcpy(app_level_blockwise_buf, app_level_blockwise_def_val, sizeof(app_level_blockwise_buf)); // global-buffer-overflow

    memset(lib_level_blockwise_buf, 0, sizeof(lib_level_blockwise_buf));
    memcpy(lib_level_blockwise_buf, lib_level_blockwise_def_val, sizeof(lib_level_blockwise_buf));

    return coap_msg_set_code(resp, COAP_MSG_SUCCESS, COAP_MSG_CONTENT);
}
```
## ASAN Log

```bash
==2889303==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000004f6581 at pc 0x0000004958c7 bp 0x7ffe84583650 sp 0x7ffe84582e18
READ of size 40 at 0x0000004f6581 thread T0
    #0 0x4958c6 in __asan_memcpy (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4958c6)
    #1 0x4c6c21 in server_handle_reset (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4c6c21)
    #2 0x4c66aa in server_handle (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4c66aa)
    #3 0x4d2543 in coap_server_exchange (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4d2543)
    #4 0x4d0071 in coap_server_run (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4d0071)
    #5 0x4c64c2 in main (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4c64c2)
    #6 0x7f3e50eb0082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #7 0x41c3fd in _start (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x41c3fd)

0x0000004f6581 is located 63 bytes to the left of global variable '<string literal>' defined in 'test_coap_server.c:96:44' (0x4f65c0) of size 73
  '<string literal>' is ascii string '0123456789abcdefghijABCDEFGHIJasdfghjklpqlfktnghrexi49s1zlkdfiecvntfbghq'
0x0000004f6581 is located 0 bytes to the right of global variable '<string literal>' defined in 'test_coap_server.c:90:44' (0x4f6580) of size 1
  '<string literal>' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow (/home/user/FreeCoAP/test/test_coap_server/test_coap_server+0x4958c6) in __asan_memcpy
Shadow bytes around the buggy address:
  0x000080096c60: 00 07 f9 f9 f9 f9 f9 f9 00 02 f9 f9 f9 f9 f9 f9
  0x000080096c70: 07 f9 f9 f9 f9 f9 f9 f9 00 00 00 03 f9 f9 f9 f9
  0x000080096c80: 00 00 03 f9 f9 f9 f9 f9 00 00 00 06 f9 f9 f9 f9
  0x000080096c90: 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x000080096ca0: 00 02 f9 f9 f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9
=>0x000080096cb0:[01]f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x000080096cc0: 00 01 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 05 f9
  0x000080096cd0: f9 f9 f9 f9 00 00 00 00 00 00 00 02 f9 f9 f9 f9
  0x000080096ce0: 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
  0x000080096cf0: f9 f9 f9 f9 00 00 00 00 00 06 f9 f9 f9 f9 f9 f9
  0x000080096d00: 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2889303==ABORTING

**Comment by keith-cullen** [comment]
Fixed
